# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/s1231174/Assembler/microprocessor/MicroProcessor.cache/wt [current_project]
set_property parent.project_path /home/s1231174/Assembler/microprocessor/MicroProcessor.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  /home/s1231174/Assembler/microprocessor/MicroProcessor.srcs/sources_1/imports/mouseCode/GenericCounter.v
  /home/s1231174/Assembler/microprocessor/MicroProcessor.srcs/sources_1/imports/new/BasicStateMachine.v
  /home/s1231174/Assembler/microprocessor/MicroProcessor.srcs/sources_1/new/ALU.v
  /home/s1231174/Assembler/microprocessor/MicroProcessor.srcs/sources_1/imports/new/IRTransmitterSM.v
  /home/s1231174/Assembler/microprocessor/MicroProcessor.srcs/sources_1/new/Processor.v
  /home/s1231174/Assembler/microprocessor/MicroProcessor.srcs/sources_1/imports/new/IRTransmitterWrapper.v
  /home/s1231174/Assembler/microprocessor/MicroProcessor.srcs/sources_1/new/Timer.v
  /home/s1231174/Assembler/microprocessor/MicroProcessor.srcs/sources_1/new/ROM.v
  /home/s1231174/Assembler/microprocessor/MicroProcessor.srcs/sources_1/new/RAM.v
  /home/s1231174/Assembler/microprocessor/MicroProcessor.srcs/sources_1/new/Wrapper.v
}
read_xdc /home/s1231174/Assembler/microprocessor/MicroProcessor.srcs/constrs_1/imports/new/DSL_VGA.xdc
set_property used_in_implementation false [get_files /home/s1231174/Assembler/microprocessor/MicroProcessor.srcs/constrs_1/imports/new/DSL_VGA.xdc]

synth_design -top Wrapper -part xc7a35tcpg236-1
write_checkpoint -noxdef Wrapper.dcp
catch { report_utilization -file Wrapper_utilization_synth.rpt -pb Wrapper_utilization_synth.pb }
