#RESET button 
set_property PACKAGE_PIN U18 [get_ports Reset]
    set_property IOSTANDARD LVCMOS33 [get_ports Reset]

#100MHz Clock
set_property PACKAGE_PIN W5 [get_ports CLK]
    set_property IOSTANDARD LVCMOS33 [get_ports CLK]
    
#PS2 Mouse Data and Clock
set_property PACKAGE_PIN C17 [get_ports CLK_MOUSE]	
    set_property IOSTANDARD LVCMOS33 [get_ports CLK_MOUSE]
        set_property PULLUP true [get_ports CLK_MOUSE]
set_property PACKAGE_PIN B17 [get_ports DATA_MOUSE]
	set_property IOSTANDARD LVCMOS33 [get_ports DATA_MOUSE]
		set_property PULLUP true [get_ports DATA_MOUSE] 
    
#segment select one of 4
set_property PACKAGE_PIN U2 [get_ports SEG_SELECT_OUT[0]]
    set_property IOSTANDARD LVCMOS33 [get_ports SEG_SELECT_OUT[0]]
set_property PACKAGE_PIN U4 [get_ports SEG_SELECT_OUT[1]]
    set_property IOSTANDARD LVCMOS33 [get_ports SEG_SELECT_OUT[1]]
set_property PACKAGE_PIN V4 [get_ports SEG_SELECT_OUT[2]]
    set_property IOSTANDARD LVCMOS33 [get_ports SEG_SELECT_OUT[2]]
set_property PACKAGE_PIN W4 [get_ports SEG_SELECT_OUT[3]]
    set_property IOSTANDARD LVCMOS33 [get_ports SEG_SELECT_OUT[3]]
    
#decimal out number with a dot
set_property PACKAGE_PIN W7 [get_ports DEC_OUT[0]]
    set_property IOSTANDARD LVCMOS33 [get_ports DEC_OUT[0]]
set_property PACKAGE_PIN W6 [get_ports DEC_OUT[1]]
    set_property IOSTANDARD LVCMOS33 [get_ports DEC_OUT[1]]
set_property PACKAGE_PIN U8 [get_ports DEC_OUT[2]]
    set_property IOSTANDARD LVCMOS33 [get_ports DEC_OUT[2]]
set_property PACKAGE_PIN V8 [get_ports DEC_OUT[3]]
    set_property IOSTANDARD LVCMOS33 [get_ports DEC_OUT[3]]
set_property PACKAGE_PIN U5 [get_ports DEC_OUT[4]]
    set_property IOSTANDARD LVCMOS33 [get_ports DEC_OUT[4]]
set_property PACKAGE_PIN V5 [get_ports DEC_OUT[5]]
    set_property IOSTANDARD LVCMOS33 [get_ports DEC_OUT[5]]
set_property PACKAGE_PIN U7 [get_ports DEC_OUT[6]]
    set_property IOSTANDARD LVCMOS33 [get_ports DEC_OUT[6]]
set_property PACKAGE_PIN V7 [get_ports DEC_OUT[7]]
    set_property IOSTANDARD LVCMOS33 [get_ports DEC_OUT[7]]
    
#Input SlideSwitches
set_property PACKAGE_PIN V17 [get_ports SLIDE_SWITCHES[0]]
    set_property IOSTANDARD LVCMOS33 [get_ports SLIDE_SWITCHES[0]]
set_property PACKAGE_PIN V16 [get_ports SLIDE_SWITCHES[1]]
    set_property IOSTANDARD LVCMOS33 [get_ports SLIDE_SWITCHES[1]]
set_property PACKAGE_PIN W16 [get_ports SLIDE_SWITCHES[2]]
    set_property IOSTANDARD LVCMOS33 [get_ports SLIDE_SWITCHES[2]]
set_property PACKAGE_PIN W17 [get_ports SLIDE_SWITCHES[3]]
    set_property IOSTANDARD LVCMOS33 [get_ports SLIDE_SWITCHES[3]]
set_property PACKAGE_PIN W15 [get_ports SLIDE_SWITCHES[4]]
    set_property IOSTANDARD LVCMOS33 [get_ports SLIDE_SWITCHES[4]]
set_property PACKAGE_PIN V15 [get_ports SLIDE_SWITCHES[5]]
    set_property IOSTANDARD LVCMOS33 [get_ports SLIDE_SWITCHES[5]]
set_property PACKAGE_PIN W14 [get_ports SLIDE_SWITCHES[6]]
    set_property IOSTANDARD LVCMOS33 [get_ports SLIDE_SWITCHES[6]]
set_property PACKAGE_PIN W13 [get_ports SLIDE_SWITCHES[7]]
    set_property IOSTANDARD LVCMOS33 [get_ports SLIDE_SWITCHES[7]]    
    
#output LED
set_property PACKAGE_PIN U16 [get_ports LED[0]]
    set_property IOSTANDARD LVCMOS33 [get_ports LED[0]]
set_property PACKAGE_PIN E19 [get_ports LED[1]]
    set_property IOSTANDARD LVCMOS33 [get_ports LED[1]]
set_property PACKAGE_PIN U19 [get_ports LED[2]]
    set_property IOSTANDARD LVCMOS33 [get_ports LED[2]]
set_property PACKAGE_PIN V19 [get_ports LED[3]]
    set_property IOSTANDARD LVCMOS33 [get_ports LED[3]]
set_property PACKAGE_PIN W18 [get_ports LED[4]]
    set_property IOSTANDARD LVCMOS33 [get_ports LED[4]]
set_property PACKAGE_PIN U15 [get_ports LED[5]]
    set_property IOSTANDARD LVCMOS33 [get_ports LED[5]]
set_property PACKAGE_PIN U14 [get_ports LED[6]]
    set_property IOSTANDARD LVCMOS33 [get_ports LED[6]]
set_property PACKAGE_PIN V14 [get_ports LED[7]]
    set_property IOSTANDARD LVCMOS33 [get_ports LED[7]]
    
#output PWM LED
set_property PACKAGE_PIN V13 [get_ports PWM_LED[0]]
    set_property IOSTANDARD LVCMOS33 [get_ports PWM_LED[0]]
set_property PACKAGE_PIN V3 [get_ports PWM_LED[1]]
    set_property IOSTANDARD LVCMOS33 [get_ports PWM_LED[1]]
set_property PACKAGE_PIN W3 [get_ports PWM_LED[2]]
    set_property IOSTANDARD LVCMOS33 [get_ports PWM_LED[2]]
set_property PACKAGE_PIN U3 [get_ports PWM_LED[3]]
    set_property IOSTANDARD LVCMOS33 [get_ports PWM_LED[3]]

set_property PACKAGE_PIN L1 [get_ports LED_TEST]
    set_property IOSTANDARD LVCMOS33 [get_ports LED_TEST]
set_property PACKAGE_PIN R2 [get_ports SLIDE_TEST]
    set_property IOSTANDARD LVCMOS33 [get_ports SLIDE_TEST]
